"""КОНТУР-ПРО: оборудование и цены."""

from __future__ import annotations

from typing import Any, Final

# --- Категории оборудования ---
CATEGORIES: Final[dict[str, dict[str, Any]]] = {
    "power": {"name": "Силовое", "color_key": "device_power", "trace_key": "trace_power", "demand": 0.7},
    "it": {"name": "ИТ", "color_key": "device_it", "trace_key": "trace_power", "demand": 0.9},
    "network": {"name": "Сеть", "color_key": "device_net", "trace_key": "trace_net", "demand": 0.8},
    "camera": {"name": "Видео", "color_key": "device_cam", "trace_key": "trace_cam", "demand": 0.95},
    "skud": {"name": "СКУД", "color_key": "device_skud", "trace_key": "trace_skud", "demand": 0.85},
    "ops": {"name": "ОПС", "color_key": "device_ops", "trace_key": "trace_ops", "demand": 0.9},
    "hvac": {"name": "ОВК", "color_key": "device_hvac", "trace_key": "trace_power", "demand": 0.8},
    "lighting": {"name": "Освещение", "color_key": "device_light", "trace_key": "trace_power", "demand": 0.6},
    "lan": {"name": "ЛВС", "color_key": "device_lan", "trace_key": "trace_net", "demand": 0.85},
    "phone": {"name": "Телефония", "color_key": "device_phone", "trace_key": "trace_net", "demand": 0.7},
    "custom": {
        "name": "Пользовательское",
        "color_key": "device_custom",
        "trace_key": "trace_power",
        "demand": 0.7,
    },
}

# --- Библиотека оборудования (30 типов) ---
EQUIPMENT_LIBRARY: Final[list[dict[str, Any]]] = [
    {
        "id": "pc",
        "name": "Рабочее место (ПК)",
        "power_w": 450,
        "category": "it",
        "icon": "💻",
        "voltage": 220,
        "price": 35000,
    },
    {
        "id": "server",
        "name": "Сервер 1U",
        "power_w": 500,
        "category": "it",
        "icon": "🖥️",
        "voltage": 220,
        "price": 120000,
    },
    {
        "id": "rack42u",
        "name": "Стойка 42U",
        "power_w": 5000,
        "category": "it",
        "icon": "🔲",
        "voltage": 220,
        "price": 80000,
    },
    {
        "id": "switch",
        "name": "Коммутатор 48p PoE+",
        "power_w": 750,
        "category": "network",
        "icon": "🔌",
        "voltage": 220,
        "price": 45000,
    },
    {
        "id": "router",
        "name": "Маршрутизатор",
        "power_w": 200,
        "category": "network",
        "icon": "🌐",
        "voltage": 220,
        "price": 25000,
    },
    {
        "id": "wifi",
        "name": "Точка Wi-Fi",
        "power_w": 30,
        "category": "network",
        "icon": "📡",
        "voltage": 220,
        "price": 5000,
    },
    {
        "id": "camera_ip",
        "name": "IP-камера PoE",
        "power_w": 25,
        "category": "camera",
        "icon": "🎥",
        "voltage": 220,
        "price": 8000,
    },
    {
        "id": "camera_ptz",
        "name": "PTZ-камера PoE+",
        "power_w": 60,
        "category": "camera",
        "icon": "📷",
        "voltage": 220,
        "price": 25000,
    },
    {
        "id": "nvr",
        "name": "NVR видеосервер",
        "power_w": 400,
        "category": "camera",
        "icon": "💾",
        "voltage": 220,
        "price": 80000,
    },
    {
        "id": "skud_ctrl",
        "name": "Контроллер СКУД",
        "power_w": 50,
        "category": "skud",
        "icon": "🔑",
        "voltage": 220,
        "price": 15000,
    },
    {
        "id": "skud_lock",
        "name": "Замок электромагнитный",
        "power_w": 15,
        "category": "skud",
        "icon": "🚪",
        "voltage": 220,
        "price": 4000,
    },
    {
        "id": "skud_reader",
        "name": "Считыватель карт",
        "power_w": 5,
        "category": "skud",
        "icon": "🪪",
        "voltage": 220,
        "price": 3000,
    },
    {
        "id": "skud_turnstile",
        "name": "Турникет",
        "power_w": 120,
        "category": "skud",
        "icon": "🚷",
        "voltage": 220,
        "price": 45000,
    },
    {
        "id": "ops_panel",
        "name": "Прибор ОПС",
        "power_w": 80,
        "category": "ops",
        "icon": "🔥",
        "voltage": 220,
        "price": 20000,
    },
    {
        "id": "ops_smoke",
        "name": "Датчик дымовой",
        "power_w": 3,
        "category": "ops",
        "icon": "💨",
        "voltage": 220,
        "price": 800,
    },
    {
        "id": "ops_heat",
        "name": "Датчик тепловой",
        "power_w": 3,
        "category": "ops",
        "icon": "🌡️",
        "voltage": 220,
        "price": 600,
    },
    {
        "id": "ops_manual",
        "name": "ИПР (ручной)",
        "power_w": 2,
        "category": "ops",
        "icon": "🔴",
        "voltage": 220,
        "price": 500,
    },
    {
        "id": "ops_siren",
        "name": "Сирена оповещения",
        "power_w": 30,
        "category": "ops",
        "icon": "📢",
        "voltage": 220,
        "price": 2500,
    },
    {
        "id": "ups",
        "name": "ИБП онлайн",
        "power_w": 0,
        "category": "power",
        "icon": "🔋",
        "voltage": 220,
        "price": 60000,
    },
    {
        "id": "ac_unit",
        "name": "Кондиционер",
        "power_w": 2000,
        "category": "hvac",
        "icon": "❄️",
        "voltage": 220,
        "price": 35000,
    },
    {
        "id": "precise_ac",
        "name": "Прецизионный кондиционер",
        "power_w": 5000,
        "category": "hvac",
        "icon": "🌡️",
        "voltage": 220,
        "price": 150000,
    },
    {
        "id": "lighting_panel",
        "name": "Щит освещения",
        "power_w": 1000,
        "category": "lighting",
        "icon": "💡",
        "voltage": 220,
        "price": 8000,
    },
    {
        "id": "breaker",
        "name": "Автоматический выключатель",
        "power_w": 0,
        "category": "power",
        "icon": "⚡",
        "voltage": 220,
        "price": 1500,
    },
    {
        "id": "outlet",
        "name": "Розеточная группа",
        "power_w": 500,
        "category": "power",
        "icon": "🔌",
        "voltage": 220,
        "price": 2500,
    },
    {
        "id": "shelf",
        "name": "Щит этажный ЩРО",
        "power_w": 0,
        "category": "power",
        "icon": "🏠",
        "voltage": 220,
        "price": 15000,
    },
    {
        "id": "patch_panel",
        "name": "Патч-панель 24p",
        "power_w": 10,
        "category": "lan",
        "icon": "🔲",
        "voltage": 220,
        "price": 8000,
    },
    {
        "id": "server_rack",
        "name": "Серверный шкаф 24U",
        "power_w": 3000,
        "category": "lan",
        "icon": "🗄️",
        "voltage": 220,
        "price": 55000,
    },
    {
        "id": "ip_phone",
        "name": "IP-телефон",
        "power_w": 15,
        "category": "phone",
        "icon": "📞",
        "voltage": 220,
        "price": 12000,
    },
    {
        "id": "intercom",
        "name": "Домофонная станция",
        "power_w": 40,
        "category": "skud",
        "icon": "🎙️",
        "voltage": 220,
        "price": 18000,
    },
    {
        "id": "cable_tray",
        "name": "Кабельный лоток 100мм",
        "power_w": 0,
        "category": "lan",
        "icon": "📋",
        "voltage": 0,
        "price": 2000,
    },
]

# --- Прайс-лист ---
PRICE_LIST: Final[dict[str, float]] = {item["id"]: item.get("price", 0) for item in EQUIPMENT_LIBRARY}
